export const $ = (id) => document.getElementById(id);

export const dom = {
  categoriesGrid: $('categoriesGrid'),
  productsGrid: $('productsGrid'),
  loadingState: $('loadingState'),
  emptyState: $('emptyState'),
  loadMoreRow: $('loadMoreRow'),
  loadMoreBtn: $('loadMoreBtn'),
  loadMoreNote: $('loadMoreNote'),
  cartBtn: $('cartBtn'),
  cartBadge: $('cartBadge'),
  cartDrawer: $('cartDrawer'),
  cartCloseBtn: $('cartCloseBtn'),
  cartBody: $('cartBody'),
  cartEmpty: $('cartEmpty'),
  cartFooter: $('cartFooterPanel'),
  cartSubtotal: $('cartSubtotal'),
  cartCountLabel: $('cartCountLabel'),
  checkoutBtn: $('checkoutBtn'),
  checkoutTNBtn: $('checkoutTNBtn'),
  overlay: $('overlay'),
  toast: $('toast'),
  searchInput: $('searchInput'),
  searchBtn: $('searchBtn'),
  searchToggle: $('searchToggle'),
  searchExpand: $('searchExpand'),
  searchResults: $('searchResults'),
  hamburger: $('hamburger'),
  navLinks: $('navLinks'),
  navbar: $('navbar'),
  productModal: $('productModal'),
  pmClose: $('pmClose'),
  pmMainImg: $('pmMainImg'),
  pmThumbs: $('pmThumbs'),
  pmTitle: $('pmTitle'),
  pmPrice: $('pmPrice'),
  pmCompare: $('pmCompare'),
  pmDescription: $('pmDescription'),
  pmVariants: $('pmVariants'),
  pmRelated: $('pmRelated'),
  pmRelatedGrid: $('pmRelatedGrid'),
  pmBuyNow: $('pmBuyNow'),
  pmAddToCart: $('pmAddToCart'),
  pmWhatsApp: $('pmWhatsApp'),
  announceBar: $('announceBar'),
  announceClose: $('announceClose'),
  backTop: $('backTop'),
  scrollProgress: $('scrollProgress'),
  currentYear: $('currentYear'),
  leafContainer: $('leafContainer'),
};

export function getNavLinks() {
  return Array.from(document.querySelectorAll('.nav-link'));
}
